const PLANDAR_CUSTOM_REPSOITORY = 'PLANDAR_CUSTOM_REPSOITORY';

const ENV_PROVIDER = 'ENV_PROVIDER';

const IS_PUBLIC_KEY = 'isPublic';

export { PLANDAR_CUSTOM_REPSOITORY, ENV_PROVIDER, IS_PUBLIC_KEY };
